#uk
base_url_ger = "https://www.killerinktattoo.de/"
expected_title = "Tattoo Zubehör - Killer Ink"
login_button = "//a[@href='https://www.killerinktattoo.de/customer/account/login/']"
email_address = "//input[@id='email']"
password = "//input[@id='pass']"
submit_login_button = "//button[@id='send2']"
create_account_button = "//a[contains(text(),'Erstelle ein Kundenkonto')]"
create_new_customer_account = "//h1[contains(text(),'Erstelle ein neues Kundenkonto')]"
account_information = "//span[contains(text(),'Account Information')]"
login_error_popup = "//div[contains(text(),'Die Anmeldedaten sind inkorrekt oder dein Kundenko')]"
search_bar = "//input[@id='search']"
search_bar_go_button = "//button[contains(text(),'Suchen')]"
basket_button = "//a[@href='https://www.killerinktattoo.de/checkout/cart']"
xion_machine = "//a[contains(text(),'Microbeau Spektra Xion S Rotary-Maschine')]"
add_to_cart = "//button[@id='product-addtocart-button']"
basket_item = "//a[contains(text(), 'Microbeau Spektra Xion S Rotary-Maschine')]"
remove_item = "//a[@class='button quantity-update__button quantity-update__button--remove cart-list-item__actions-item active']"
empty_shopping_cart = "//p[contains(text(),'Sie haben keine Artikel in Ihrem Warenkorb.')]"
close_icon = "//button[@class='button button--outline button--fluid' and @data-role='closeBtn']"
remove_all_button = "//a[contains(text(),'Alle entfernen')]"
are_you_sure = "//span[contains(text(),'OK')]"
cookie_button = "//a[contains(text(),'Akzeptiere alle Cookies')]"
