# uk
base_url_uk = "https://www.killerinktattoo.co.uk/"
expected_title = "Tattoo Supplies and Tattoo Equipment from Killer Ink Tattoo"
login_button = "//a[@href='https://www.killerinktattoo.co.uk/customer/account/login/']"
email_address = "//input[@id='email']"
password = "//input[@id='pass']"
submit_login_button = "//button[@id='send2']"
create_account_button = "//a[contains(text(),'Create an Account')]"
create_new_customer_account = "//h1[contains(text(),'Create New Customer Account')]"
account_information = "//span[contains(text(),'Account Information')]"
login_error_popup = "//div[contains(text(),'The account sign-in was incorrect or your account ')]"
search_bar = "//input[@id='search']"
search_bar_go_button = "//button[contains(text(),'Go')]"
basket_button = "//a[@href='https://www.killerinktattoo.co.uk/checkout/cart']"
xion_machine = "//a[@title='FK Irons Spektra Xion Rotary Machine in Stealth']"
add_to_cart = "//button[@id='product-addtocart-button']"
basket_item = "//a[contains(text(), 'FK Irons Spektra Xion Rotary Machine in Stealth')]"
remove_item = "//a[@class='button quantity-update__button quantity-update__button--remove cart-list-item__actions-item active']"
empty_shopping_cart = "//p[contains(text(),'You have no items in your shopping cart.')]"
close_icon = "//button[@class='button button--outline button--fluid' and @data-role='closeBtn']"
remove_all_button = "//a[contains(text(),'Remove All')]"
are_you_sure = "//button[@class='button action-primary action-accept' and span[normalize-space(text())='OK']]"
cookie_button = "//a[@class='action accept-all button button--primary' and text()='Allow All']"
youtube = "//h2[contains(text(),'Youtube')]"
logout_button = "//a[contains(text(),'Logout')]"
proceed_to_checkout_button = "//span[contains(text(),'Proceed to Checkout')]"
estimate_shipping_dropdown = '//body[1]/div[4]/main[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/svg[2]/g[1]/g[1]/path[1]'
estimate_shipping_close = "//g[@id='ki_tattoo_needle_cartridges']/path[@id='']"
ZIP_Postal_code = "//input[@id='W2KU52M']"
DPD_standard_radio = "//input[@type='radio' and @value='shqDPD_STD' and @id='s_method_shqDPD_STD']"
order_review_page = "//h2[contains(text(),'Order Review')]"
price_element = "//div[@class='amount cart-totals__row-value' and @data-th='Order Total']/span[@class='price']"
cart_subtotal = "//div[@class='amount cart-totals__row-value' and @data-th='Cart Subtotal']"
Tax = "//span[@class='price' and @data-th='VAT']"
item_count = "//input[@class='cart-list-item__qty-input quantity-update__input' and @title='Qty']"
basket_screen_price = "//div[@class='cart-totals__row-value cart-totals__row-value--total']/span[@class='price']"
add_item_icon = "//button[contains(@class, 'quantity-update__button--plus')]"
bin_button = "//header/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]"
empty_basket = "//div[contains(text(),'Are you sure you would like to remove this item fr')]"
are_you_sure_overlay = "/html[1]/body[1]/div[9]/aside[2]/div[2]/footer[1]/button[2]"
