#ire
base_url_ie = "https://www.killerinktattoo.ie/"
expected_title = "Tattoo Supplies and Tattoo Equipment from Killer Ink Tattoo"
login_button = "//a[@href='https://www.killerinktattoo.ie/customer/account/login/']"
submit_login_button = "//button[@id='send2']"
account_information = "//span[contains(text(),'Account Information')]"
email_address = "//input[@id='email']"
password = "//input[@id='pass']"
create_account_button = "//a[contains(text(),'Create an Account')]"
create_new_customer_account = "//h1[contains(text(),'Create New Customer Account')]"
login_error_popup = "//div[contains(text(),'The account sign-in was incorrect or your account ')]"
xion_machine = "//a[@title='FK Irons Spektra Xion Rotary Machine in Stealth']"
add_to_cart = "//button[@id='product-addtocart-button']"
basket_item = "//a[contains(text(), 'FK Irons Spektra Xion Rotary Machine in Stealth')]"
remove_item = "//a[@class='button quantity-update__button quantity-update__button--remove cart-list-item__actions-item active']"
empty_shopping_cart = "//p[contains(text(),'You have no items in your shopping cart.')]"
close_icon = "//button[@class='button button--outline button--fluid' and @data-role='closeBtn']"
remove_all_button = "//a[contains(text(),'Remove All')]"
are_you_sure = "//span[contains(text(),'OK')]"
basket_button = "//a[@href='https://www.killerinktattoo.ie/checkout/cart']"
search_bar = "//input[@id='search']"
search_bar_go_button = "//button[contains(text(),'Go')]"
cookie_button = "//a[contains(text(),'Accept all cookies')]"
